spring:
  application:
    name: mercadoapp
  jpa:
    hibernate:
#      Quitar esta config cuando este en produccion
      ddl-auto: 'create-drop'

    show-sql: true
  h2:
    console:
      enabled: true