spring:
  application:
    name: mercadoapp
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: 'create-only'
    show-sql: true
  datasource:
    url: ${URL_DB}
    driver-class-name: org.postgresql.Driver
