CREATE TABLE products
(
    ID   BIGINT       NOT NULL,
    name VARCHAR(255) NOT NULL,
    unit VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE revoked_tokens
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMP   NOT NULL,
    CONSTRAINT uq_revoked_tokens_token_hash UNIQUE (token_hash)
);

CREATE INDEX idx_revoked_tokens_token_hash ON revoked_tokens (token_hash);