name: CD
run-name: "Continuous Deployment(CD) -- ${{ github.actor }}. ID: ${{ github.run_id }}"
on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Trigger Render Deploy
        run: |
          curl -X POST "${{ secrets.RRENDER_DEPLOY_HOOK_URL }}"